### ISSUE TITLE
多环境下的怎么动态获取数据源配置

### ISSUE THREAD

**Issue by baikeqin** [bingoohuang/eql#19]
多环境下的怎么动态获取数据源配置
比如：使用@EqlerConfig("params")，此处的params是动态获取的，请大神给个解决的方案，谢谢

**Comment by bingoohuang** [comment]
参考多数据源Mtcp的实现

https://github.com/bingoohuang/eql/blob/master/src/test/java/org/n3r/eql/mtcp/MtcpEqler.java
